### ISSUE TITLE
Enter does not send a newline (`\n`)

### ISSUE THREAD

**Issue by pegvin** [adamharrison/lite-xl-terminal#17]
I am on Debian Linux, and installed this plugin manually using the single liner command in the README.md.

everything works like charm but pressing enter key doesn't execute the comand, i.e. enter key does not send a newline character.

**Comment by Guldoman** [comment]
What shell are you using?

**Comment by adamharrison** [comment]
Yeah; this is something that I was hoping was only confined to me, but may also be in other cases too. My guess is `zsh`.

Right now, on Linux, we emit `\r` as a newline, because we've set the ICRNL, so this gets translated to a newline. I'm not sure why this is what we're doing, only that it seems to have the best compatibility amongst all programs I tested, and all shells. Except `zsh`. But `zsh` works for Guldo. No idea why.

I am very much open to suggestions here.

**Comment by adamharrison** [comment]
Never mind, I did a dumb. Lol. Sigh. Fixing...

**Comment by adamharrison** [comment]
@pegvin Try 5590ce568bf81b66ac4ad44ef456824bb5cde4d0 / master.

**Comment by pegvin** [comment]
Yay! it works now, and yes you guessed it right, i was indeed using zsh.

thanks for doing the magic you magicians!
